// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/matveevaolga/request-managing-app/internal/domain/repository (interfaces: ApplicationRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/matveevaolga/request-managing-app/internal/domain"
	repository "github.com/matveevaolga/request-managing-app/internal/domain/repository"
)

// MockApplicationRepository is a mock of ApplicationRepository interface.
type MockApplicationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationRepositoryMockRecorder
}

// MockApplicationRepositoryMockRecorder is the mock recorder for MockApplicationRepository.
type MockApplicationRepositoryMockRecorder struct {
	mock *MockApplicationRepository
}

// NewMockApplicationRepository creates a new mock instance.
func NewMockApplicationRepository(ctrl *gomock.Controller) *MockApplicationRepository {
	mock := &MockApplicationRepository{ctrl: ctrl}
	mock.recorder = &MockApplicationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationRepository) EXPECT() *MockApplicationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockApplicationRepository) Create(arg0 context.Context, arg1 *domain.Application) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApplicationRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApplicationRepository)(nil).Create), arg0, arg1)
}

// GetAllFiltered mocks base method.
func (m *MockApplicationRepository) GetAllFiltered(arg0 context.Context, arg1 repository.ApplicationFilterParameters) ([]domain.ApplicationPreview, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFiltered", arg0, arg1)
	ret0, _ := ret[0].([]domain.ApplicationPreview)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllFiltered indicates an expected call of GetAllFiltered.
func (mr *MockApplicationRepositoryMockRecorder) GetAllFiltered(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFiltered", reflect.TypeOf((*MockApplicationRepository)(nil).GetAllFiltered), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockApplicationRepository) GetByID(arg0 context.Context, arg1 int64) (*domain.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockApplicationRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockApplicationRepository)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockApplicationRepository) Update(arg0 context.Context, arg1 *domain.Application) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApplicationRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApplicationRepository)(nil).Update), arg0, arg1)
}

// UpdateStatus mocks base method.
func (m *MockApplicationRepository) UpdateStatus(arg0 context.Context, arg1 int64, arg2 domain.ApplicationStatus, arg3 *int64, arg4 *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockApplicationRepositoryMockRecorder) UpdateStatus(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockApplicationRepository)(nil).UpdateStatus), arg0, arg1, arg2, arg3, arg4)
}
