// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/matveevaolga/request-managing-app/internal/domain/repository (interfaces: ProjectTypeRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/matveevaolga/request-managing-app/internal/domain"
)

// MockProjectTypeRepository is a mock of ProjectTypeRepository interface.
type MockProjectTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectTypeRepositoryMockRecorder
}

// MockProjectTypeRepositoryMockRecorder is the mock recorder for MockProjectTypeRepository.
type MockProjectTypeRepositoryMockRecorder struct {
	mock *MockProjectTypeRepository
}

// NewMockProjectTypeRepository creates a new mock instance.
func NewMockProjectTypeRepository(ctrl *gomock.Controller) *MockProjectTypeRepository {
	mock := &MockProjectTypeRepository{ctrl: ctrl}
	mock.recorder = &MockProjectTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectTypeRepository) EXPECT() *MockProjectTypeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectTypeRepository) Create(arg0 context.Context, arg1 *domain.ProjectType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectTypeRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectTypeRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockProjectTypeRepository) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectTypeRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectTypeRepository)(nil).Delete), arg0, arg1)
}

// GetAllProjects mocks base method.
func (m *MockProjectTypeRepository) GetAllProjects(arg0 context.Context) ([]domain.ProjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProjects", arg0)
	ret0, _ := ret[0].([]domain.ProjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProjects indicates an expected call of GetAllProjects.
func (mr *MockProjectTypeRepositoryMockRecorder) GetAllProjects(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProjects", reflect.TypeOf((*MockProjectTypeRepository)(nil).GetAllProjects), arg0)
}

// GetByID mocks base method.
func (m *MockProjectTypeRepository) GetByID(arg0 context.Context, arg1 int64) (*domain.ProjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.ProjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectTypeRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectTypeRepository)(nil).GetByID), arg0, arg1)
}

// GetByName mocks base method.
func (m *MockProjectTypeRepository) GetByName(arg0 context.Context, arg1 string) (*domain.ProjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", arg0, arg1)
	ret0, _ := ret[0].(*domain.ProjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockProjectTypeRepositoryMockRecorder) GetByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockProjectTypeRepository)(nil).GetByName), arg0, arg1)
}

// Update mocks base method.
func (m *MockProjectTypeRepository) Update(arg0 context.Context, arg1 *domain.ProjectType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectTypeRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectTypeRepository)(nil).Update), arg0, arg1)
}
